package oscar.cp.perf

import oscar.perf.AppPerfTest

//Todo: maybe autodetect?
class AllAppsPerfTest extends AppPerfTest(
  AllIntervals,
  AlternativeUnary,
  BACP,
  ChemicalTanker,
  CookieMonster,
  Cubes4,
  DeBruijn,
  ElectricityMarket,
  ElementVarACPerf,
  Eternity,
  Golomb,
  Hexiom,
  JobShop,
  JobShopWithTransitionTimes,
  Langford,
  LargeScaleGreedyCumulative,
  LargeSort,
  League,
  LinearToProgram,
  LongestPath,
  LostAtSeaCircuit,
  MagicSequence,
  Nonogram,
  PatternSetMining,
  PentominoesInt,
  QuadraticAssignment,
  Queens,
  QueensJC,
  QueensJCBC,
  QueensJCDecomp,
  QueensTestDelta,
  Rack,
  RCPSP,
  RCPSP2,
  ResourceAssignment,
  SceneAllocation,
  SportSchedulingMedium,
  SportSchedulingStrong,
  StableMariage,
  Steel,
  SubCircuit,
  TSP
)